"""Install Claude Code skill + slash commands into a ``.claude`` directory.

``scripthut agent install`` writes two managed files:

- ``.claude/skills/scripthut/SKILL.md`` — a *thin* skill: the frontmatter
  description is what triggers on-demand loading, and the body's first
  instruction is to run ``scripthut agent prompt`` for the full, live,
  config-aware briefing. The inventory (backends, stacks, sources) is
  deliberately NOT baked in — it would go stale on every config edit;
  the CLI stays the single source of truth.
- ``.claude/commands/scripthut/debug.md`` — a ``/scripthut:debug [run-id]``
  slash command that walks the failure-diagnosis flow (statuses → stderr →
  classification → proposed fix).

Ownership is tracked with a marker comment so re-install never clobbers a
file the user hand-authored: files carrying the marker are ours to
overwrite; files without it are skipped unless ``force`` is set.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from scripthut import __version__

# Substring that marks a file as scripthut-managed. Kept version-free so
# ownership detection survives upgrades; the rendered line appends the
# current version for humans reading the file.
MANAGED_MARKER = "generated by `scripthut agent install`"

SKILL_RELPATH = Path("skills/scripthut/SKILL.md")
DEBUG_COMMAND_RELPATH = Path("commands/scripthut/debug.md")


def _marker_line() -> str:
    return (
        f"<!-- {MANAGED_MARKER} (scripthut v{__version__}) — "
        "re-run it to update; hand edits will be overwritten -->"
    )


def render_skill() -> str:
    """The ``scripthut`` skill: trigger description + condensed core loop."""
    return f"""\
---
name: scripthut
description: >-
  Submit and monitor compute workflows with the ScriptHut CLI — HPC
  clusters (Slurm, PBS/Torque) over SSH, AWS Batch, AWS EC2, or the
  local machine (local backend). Use when the user wants to run or
  submit a workflow, job, or compute task; check run, job, or cluster
  status; tail or inspect job logs; fetch collected outputs under
  `$SCRIPTHUT_OUTPUT_DIR`; debug a failed run; get a local data
  directory, dataset, or locally-built container onto a cluster (stage,
  copy, or scp a folder to scratch) or declare a workflow's data
  dependency; manage software stacks (venv, Conda, Julia); probe the
  result cache (would this task be a cache hit?); fetch a task's
  provenance manifest (input/output hashes); or estimate compute
  costs — not for LaTeX/Workshop build failures (latex-debug), not
  for authoring skills/rules (agent-instructions), not for dotsync
  wiring or credentials (dotsync).
---

{_marker_line()}

# ScriptHut

Drive jobs with the `scripthut` CLI. Flags, exit codes, and the live
inventory live in `scripthut agent prompt` — run it first, and again
when `scripthut.yaml` changes. Every parseable command takes `--json`.

```bash
scripthut agent prompt
```

## Verify, then submit

1. `scripthut status` — server reachable, auth working. Stop and report
   the diagnostic on failure.
2. `scripthut backend list --json`.
3. Prefer a source workflow over ad-hoc: `scripthut source list --json`,
   `scripthut source view <name> --json`.
4. Stack: `scripthut stack check <name> --json`;
   `scripthut stack install <name>` if not ready.
5. Non-trivial ad-hoc: `scripthut task run ... --dry-run`.
6. Tasks that declare `inputs`/`outputs`:
   `scripthut task probe --from-file tasks.json --backend <b> --json`
   answers hit/miss **without executing or writing anything**.

```bash
RUN_ID=$(scripthut workflow run train.json \\
  --source <name> --backend <backend> --json | jq -r .id)
```

Runs execute against latest HEAD on the source's configured branch;
`--branch <name>` selects a different branch of a git source. Ad-hoc:
`scripthut task run`, same `--json` shape.

A `type: sync` source copies git-tracked laptop files to the backend on
submit (not `output/`), then pulls `output/` back when the run ends;
`run watch` waits for that pull. Dest directories show up in
`scripthut disk scan` as live working copies; `disk clean` will not
delete them.

Background `scripthut run watch $RUN_ID --exit-status` (the local
daemon counts). Prints `Run … COMPLETED` / `Run … FAILED` with failed
task ids and a `run logs` hint; exits non-zero on failure. One-shot:
`scripthut workflow run <file> --source <name> --backend <b> --watch`
(also background). Re-poll `scripthut run view $RUN_ID --json` only
when a background watch is unavailable.

## After submit

- Status: `scripthut run view $RUN_ID --json`
- Live stdout: `scripthut run logs $RUN_ID <task_id> -f`
- FAILED stderr: `scripthut run logs $RUN_ID <task_id> --error --tail 200`
- `$SCRIPTHUT_OUTPUT_DIR` (tool logs, `task-summary.md`, plots) is **not**
  stdout: `scripthut run outputs $RUN_ID <task_id> --json`, then
  `scripthut run outputs $RUN_ID <task_id> <rel-path>`
- Manifest: `scripthut run manifest $RUN_ID <task_id>` — input hashes as
  used, output paths + content hashes, executor, timing.

| Bad | Good |
|---|---|
| `ssh … 'cat job.err'` | `scripthut run logs $RUN_ID $TASK --error --tail 200` |
| `curl …/outputs/file/…` | `scripthut run outputs $RUN_ID $TASK <path>` |
| Poll `run view` | Background `scripthut run watch $RUN_ID --exit-status` |

## Data

Do not `scp`, and do not tell the user to. Declare `datasets:` in
**user-global** config (`name` + local `path`; rejected in project-local
`scripthut.yaml`). Workflow JSON: `data: [<name>]` beside `tasks`.

Copy lands at `<dataset_dir>/<name>/<hash12>` (`dataset_dir` default
`~/scripthut-data`). An existing hash directory is reused. Tasks read
`DATA_<NAME>` (and `DATA_DIR` when the workflow has exactly one
dataset) — never hardcode the dest. Do not write into `$DATA_DIR`; the
copy is shared by every run whose data hashes the same.

Staging is async: `workflow run` returns immediately; the copy is item
`_data.<name>` that real tasks depend on. Home has a quota far below
most datasets — ask for scratch `dataset_dir` before large copies; do
not guess the path. Full rules (symlinks, empty dirs, containers):
`scripthut agent prompt`.

## Failure

`/scripthut:debug [run-id]`, or: stderr + `run outputs`, then
`stack check`, then OOM/TIMEOUT in stderr or scheduler state, then
workflow content. Failed `_data.<name>` is staging — `error` names the
cause (missing/empty local dir, broken or escaping symlink, unusable
`root`/`dataset_dir`, hash mismatch); downstream is `dep_failed`. Fix
and submit a **new** run; do not rerun the failed one.

## Gotchas

- `working_dir` and TaskDefinition paths are on the **backend**, not the
  laptop (`local` runs on the scripthut host).
- Logical partition names from `scripthut agent prompt` (`partition_map`),
  not raw cluster names.
- Result cache needs declared `outputs` and a server-side store;
  `cache_scope: "inputs"` reuses across commits only when `inputs`
  covers everything the command reads. Do not add make-style skip
  logic inside task commands.
- Local mode (no server): statuses refresh only on re-run of `run view`.
"""


def render_debug_command() -> str:
    """The ``/scripthut:debug`` slash command body."""
    return f"""\
---
description: >-
  Diagnose a failed ScriptHut run — fetch statuses, stderr, and
  collected outputs; classify the failure; propose a fix
argument-hint: [run-id]
---

{_marker_line()}

Diagnose ScriptHut run `$ARGUMENTS`. If no run id was given, take the
most recent failed run from `scripthut run list --json`.

1. `scripthut run view <run-id> --json` — FAILED / dep_failed items;
   scheduler state (OOM, TIMEOUT, NODE_FAIL, CANCELLED).
2. Each failed task:
   `scripthut run logs <run-id> <task-id> --error --tail 200`
   (stdout `--tail 200` if stderr is empty).
   Then `scripthut run outputs <run-id> <task-id> --json` and fetch
   `.log` / `task-summary.md`. `run logs` is not `$SCRIPTHUT_OUTPUT_DIR`.
3. Classify:
   - **Stack not ready** — `scripthut stack check <name> --json`; offer
     `scripthut stack install <name>`.
   - **Resource limit** — OOM/TIMEOUT; name the field to bump
     (`memory`, `time_limit`, `cpus`).
   - **Stale cache hit** — `cache_hit: true` / `CACHED`. Inspect
     `scripthut run manifest <run-id> <task-id>`: if the task reads
     files its declared `inputs` don't cover (`cache_scope: "inputs"`
     risk), fix `inputs` or set `cache: false` and resubmit.
   - **Code/workflow** — quote the failing lines; name the source file
     if it is in this repo.
4. Report cause and fix. Resubmit only if asked, as a **new** run.
   Unmerged git-source fix: `scripthut workflow run <file> --source
   <name> --branch <fix-branch> --watch` (background) before merge.
"""


@dataclass
class InstallResult:
    """Outcome of installing one managed file."""

    path: Path
    action: str  # created | updated | unchanged | skipped


def _install_one(path: Path, content: str, force: bool) -> InstallResult:
    # A symlink here means the target is managed by something else — commonly
    # a dotfiles repo linking its own hand-written skill into ~/.claude. Writing
    # through it would silently edit that repo, which --force must not be able
    # to do: the flag means "overwrite an unmanaged file", not "follow a link
    # out of the directory the user pointed at".
    if path.is_symlink():
        return InstallResult(path, "skipped")
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return InstallResult(path, "unchanged")
        if MANAGED_MARKER not in existing and not force:
            return InstallResult(path, "skipped")
        action = "updated"
    else:
        action = "created"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return InstallResult(path, action)


def install_assets(claude_dir: Path, force: bool = False) -> list[InstallResult]:
    """Write the skill and slash-command files under ``claude_dir``.

    ``claude_dir`` is the ``.claude`` directory itself (project-level
    ``<repo>/.claude`` or user-level ``~/.claude``).
    """
    return [
        _install_one(claude_dir / SKILL_RELPATH, render_skill(), force),
        _install_one(claude_dir / DEBUG_COMMAND_RELPATH, render_debug_command(), force),
    ]
