"""Install Claude Code skill + slash commands into a ``.claude`` directory.

``scripthut agent install`` writes two managed files:

- ``.claude/skills/scripthut/SKILL.md`` — a *thin* skill: the frontmatter
  description is what triggers on-demand loading, and the body's first
  instruction is to run ``scripthut agent prompt`` for the full, live,
  config-aware briefing. The inventory (backends, stacks, sources) is
  deliberately NOT baked in — it would go stale on every config edit;
  the CLI stays the single source of truth.
- ``.claude/commands/scripthut/debug.md`` — a ``/scripthut:debug [run-id]``
  slash command that walks the failure-diagnosis flow (statuses → stderr →
  classification → proposed fix).

Ownership is tracked with a marker comment so re-install never clobbers a
file the user hand-authored: files carrying the marker are ours to
overwrite; files without it are skipped unless ``force`` is set.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from scripthut import __version__

# Substring that marks a file as scripthut-managed. Kept version-free so
# ownership detection survives upgrades; the rendered line appends the
# current version for humans reading the file.
MANAGED_MARKER = "generated by `scripthut agent install`"

SKILL_RELPATH = Path("skills/scripthut/SKILL.md")
DEBUG_COMMAND_RELPATH = Path("commands/scripthut/debug.md")


def _marker_line() -> str:
    return (
        f"<!-- {MANAGED_MARKER} (scripthut v{__version__}) — "
        "re-run it to update; hand edits will be overwritten -->"
    )


def render_skill() -> str:
    """The ``scripthut`` skill: trigger description + condensed core loop."""
    return f"""\
---
name: scripthut
description: >-
  Submit and monitor compute workflows with the ScriptHut CLI — HPC
  clusters (Slurm, PBS/Torque) over SSH, AWS Batch, AWS EC2, or the
  local machine (local backend). Use when the user wants to run or
  submit a workflow, job, or compute task; check run, job, or cluster
  status; tail or inspect job logs; debug a failed run; manage software
  stacks (venv, Conda, Julia); probe the result cache (would this task
  be a cache hit?); fetch a task's provenance manifest (input/output
  hashes); or estimate compute costs.
---

{_marker_line()}

# ScriptHut

ScriptHut runs declarative workflows (GitHub Actions-style, defined in a
git repo) on the user's own infrastructure — remote clusters, AWS, or
the scripthut host itself via a `local` backend. Everything is driven
through the `scripthut` CLI; every command supports `--json`.

## First step — always

Run this before anything else, and re-read it whenever the project's
`scripthut.yaml` changes (new backend, source, or stack):

```bash
scripthut agent prompt
```

It prints the full CLI reference **plus a live inventory** of the
backends, sources, and stacks configured for this project. Everything
below is a condensed reminder, not a substitute.

## Core loop — verify, then submit

Verify (cheap, read-only):

1. `scripthut status` — server reachable, auth working. If this fails,
   stop and report the diagnostic.
2. `scripthut backend list --json` — confirm targets are connected.
3. Prefer an existing source workflow over ad-hoc submission:
   `scripthut source list --json`, then `scripthut source view <name> --json`.
4. If a stack is involved: `scripthut stack check <name> --json`;
   `scripthut stack install <name>` if not ready.
5. `scripthut task run ... --dry-run` to preview the assembled
   TaskDefinition before submitting anything non-trivial.
6. For tasks that declare `inputs`/`outputs` (result caching):
   `scripthut task probe --from-file tasks.json --backend <b> --json`
   answers hit/miss per task **without executing or writing anything**
   — know what the cache will skip before submitting expensive work.

Submit and track:

7. Submit with `--json` and capture the run id:

   ```bash
   RUN_ID=$(scripthut workflow run train.json \\
     --source <name> --backend <backend> --json | jq -r .id)
   ```

   Runs execute against latest HEAD on the source's configured branch;
   add `--branch <name>` to run from a different branch of a git source
   (the workflow file and repo config are read at that branch's tip).
   Ad-hoc tasks use `scripthut task run` with the same `--json` shape.
8. **Get notified — don't poll.** Against a running server (the local
   daemon counts), `scripthut run watch $RUN_ID --exit-status` blocks
   until the run is terminal, prints a one-line verdict (`Run … COMPLETED`
   / `Run … FAILED` with the failed task ids and a `run logs` hint), and
   exits non-zero on failure. **Launch it as a background task** so you
   keep working and are handed that summary the instant the run finishes —
   this is how you stop missing completions. Submit and watch in one shot
   with `scripthut workflow run <file> --source <name> --backend <b>
   --watch` (also backgrounded). Fall back to re-polling
   `scripthut run view $RUN_ID --json` only when you can't background a
   task.
9. Logs: `scripthut run logs $RUN_ID <task_id> -f` to tail live;
   `--error --tail 200` first when a task ends in FAILED.
10. Provenance: `scripthut run manifest $RUN_ID <task_id>` prints the
    task's versioned manifest — input hashes as used, output paths +
    content hashes, executor, timing — for anything downstream that
    needs to verify or adopt the results.

## Failure diagnosis

Use the `/scripthut:debug [run-id]` command, or manually: read stderr,
then check stack readiness (`stack check`), resource limits (OOM/TIMEOUT
in stderr or scheduler state), and only then the workflow content. Fix
and resubmit a **new** run rather than rerunning the failed one.

## Gotchas

- `working_dir` and paths in TaskDefinitions are on the **backend**, not
  the local filesystem (a `local`-type backend runs on the scripthut
  host, so local paths are correct there).
- Partition names are logical (per `partition_map`); use the names from
  `scripthut agent prompt`, not raw cluster names.
- Result caching needs declared `outputs` (and a server-side cache
  store); `cache_scope: "inputs"` reuses across commits but is only
  safe when `inputs` covers everything the command reads. Never add
  make-style freshness checks inside task commands — declare
  `inputs`/`outputs` and let the cache decide.
- In local mode (no server), statuses only refresh when you re-run
  `run view`.
"""


def render_debug_command() -> str:
    """The ``/scripthut:debug`` slash command body."""
    return f"""\
---
description: >-
  Diagnose a failed ScriptHut run — fetch statuses and stderr, classify
  the failure, propose a fix
argument-hint: [run-id]
---

{_marker_line()}

Diagnose ScriptHut run `$ARGUMENTS`. If no run id was given, find the most
recent failed run with `scripthut run list --json`.

1. `scripthut run view <run-id> --json` — list the FAILED items and note
   any scheduler state (OOM, TIMEOUT, NODE_FAIL, CANCELLED).
2. For each failed task:
   `scripthut run logs <run-id> <task-id> --error --tail 200`
   (fall back to stdout via `--tail 200` if stderr is empty).
3. Classify the root cause:
   - **Stack not ready** — `scripthut stack check <name> --json`; offer
     `scripthut stack install <name>`.
   - **Resource limit** — OOM/TIMEOUT in stderr or scheduler state; name
     the TaskDefinition field to bump (memory, time, cpus).
   - **Stale or unexpected cache hit** — the item shows `cache_hit: true`
     / scheduler state `CACHED` but the results look wrong. Inspect
     `scripthut run manifest <run-id> <task-id>`: if the task reads
     files its declared `inputs` don't cover (a real risk with
     `cache_scope: "inputs"`), fix the `inputs` list — or set
     `cache: false` on the task — and resubmit.
   - **Code/workflow bug** — quote the failing lines from stderr and
     point at the source file if it's in this repo.
4. Report the root cause and the concrete fix. Only resubmit (as a NEW
   run — never rerun the failed one) if the user asks. If the fix lives
   on an unmerged branch of the workflow's git source, test it with
   `scripthut workflow run <file> --source <name> --branch <fix-branch>
   --watch` (run in the background to be notified of the result) before
   merging.
"""


@dataclass
class InstallResult:
    """Outcome of installing one managed file."""

    path: Path
    action: str  # created | updated | unchanged | skipped


def _install_one(path: Path, content: str, force: bool) -> InstallResult:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return InstallResult(path, "unchanged")
        if MANAGED_MARKER not in existing and not force:
            return InstallResult(path, "skipped")
        action = "updated"
    else:
        action = "created"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return InstallResult(path, action)


def install_assets(claude_dir: Path, force: bool = False) -> list[InstallResult]:
    """Write the skill and slash-command files under ``claude_dir``.

    ``claude_dir`` is the ``.claude`` directory itself (project-level
    ``<repo>/.claude`` or user-level ``~/.claude``).
    """
    return [
        _install_one(claude_dir / SKILL_RELPATH, render_skill(), force),
        _install_one(claude_dir / DEBUG_COMMAND_RELPATH, render_debug_command(), force),
    ]
